# Generated by Django 4.1.5 on 2023-01-10 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('address', models.TextField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TailleVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('prix', models.FloatField()),
                ('taille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.taillevehicule')),
                ('vehicule_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.typevehicule')),
            ],
        ),
        migrations.CreateModel(
            name='TarifLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_jour', models.FloatField()),
                ('taille_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.taillevehicule')),
                ('type_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.typevehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_location', models.DateTimeField()),
                ('date_retour', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.client')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.vehicule')),
            ],
        ),
    ]
